// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化 Rust 核心
Future<String> init() => RustLib.instance.api.crateBridgeInit();

/// 保存 JM 反混淆后的图片到磁盘
Future<void> decodeJmImageToDisk({
  required List<int> imageData,
  required int chapterId,
  required String fileName,
  required String url,
}) => RustLib.instance.api.crateBridgeDecodeJmImageToDisk(
  imageData: imageData,
  chapterId: chapterId,
  fileName: fileName,
  url: url,
);

/// 搜索漫画 (JM 源)
Future<String> jmSearch({required String keyword, required int page}) =>
    RustLib.instance.api.crateBridgeJmSearch(keyword: keyword, page: page);

/// 获取漫画详情 (JM 源)
Future<String> jmGetComicDetail({required String comicId}) =>
    RustLib.instance.api.crateBridgeJmGetComicDetail(comicId: comicId);

/// 获取章节列表 (JM 源)
Future<String> jmGetChapters({required String comicId}) =>
    RustLib.instance.api.crateBridgeJmGetChapters(comicId: comicId);

/// 获取章节图片 (JM 源)
Future<String> jmGetChapterImages({required String chapterId}) =>
    RustLib.instance.api.crateBridgeJmGetChapterImages(chapterId: chapterId);

/// 获取最新更新 (JM 源)
Future<String> jmGetLatest({required int page}) =>
    RustLib.instance.api.crateBridgeJmGetLatest(page: page);

/// 获取排行榜 (JM 源)
Future<String> jmGetRanking({
  required String category,
  required String order,
  required int page,
}) => RustLib.instance.api.crateBridgeJmGetRanking(
  category: category,
  order: order,
  page: page,
);

/// 登录哔咔
Future<String> bikaLogin({required String email, required String password}) =>
    RustLib.instance.api.crateBridgeBikaLogin(email: email, password: password);

/// 搜索漫画 (哔咔源)
Future<String> bikaSearch({
  required String keyword,
  required int page,
  required String authorization,
}) => RustLib.instance.api.crateBridgeBikaSearch(
  keyword: keyword,
  page: page,
  authorization: authorization,
);

/// 获取漫画详情 (哔咔源)
Future<String> bikaGetComicDetail({
  required String comicId,
  required String authorization,
}) => RustLib.instance.api.crateBridgeBikaGetComicDetail(
  comicId: comicId,
  authorization: authorization,
);

/// 获取章节列表 (哔咔源)
Future<String> bikaGetChapters({
  required String comicId,
  required String authorization,
}) => RustLib.instance.api.crateBridgeBikaGetChapters(
  comicId: comicId,
  authorization: authorization,
);

/// 获取章节图片 (哔咔源)
Future<String> bikaGetChapterImages({
  required String comicId,
  required int chapterOrder,
  required String authorization,
}) => RustLib.instance.api.crateBridgeBikaGetChapterImages(
  comicId: comicId,
  chapterOrder: chapterOrder,
  authorization: authorization,
);

/// 获取最新更新 (哔咔源)
Future<String> bikaGetLatest({
  required int page,
  required String authorization,
}) => RustLib.instance.api.crateBridgeBikaGetLatest(
  page: page,
  authorization: authorization,
);

/// 获取排行榜 (哔咔源)
Future<String> bikaGetRanking({
  required String category,
  required String order,
  required int page,
  required String authorization,
}) => RustLib.instance.api.crateBridgeBikaGetRanking(
  category: category,
  order: order,
  page: page,
  authorization: authorization,
);
