// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化 Rust 核心
Future<String> init() => RustLib.instance.api.crateBridgeInit();

/// 搜索漫画 (JM 源)
Future<String> jmSearch({required String keyword, required int page}) =>
    RustLib.instance.api.crateBridgeJmSearch(keyword: keyword, page: page);

/// 获取漫画详情 (JM 源)
Future<String> jmGetComicDetail({required String comicId}) =>
    RustLib.instance.api.crateBridgeJmGetComicDetail(comicId: comicId);

/// 获取章节列表 (JM 源)
Future<String> jmGetChapters({required String comicId}) =>
    RustLib.instance.api.crateBridgeJmGetChapters(comicId: comicId);

/// 获取章节图片 (JM 源)
Future<String> jmGetChapterImages({required String chapterId}) =>
    RustLib.instance.api.crateBridgeJmGetChapterImages(chapterId: chapterId);

/// 获取最新更新 (JM 源)
Future<String> jmGetLatest({required int page}) =>
    RustLib.instance.api.crateBridgeJmGetLatest(page: page);

/// 获取排行榜 (JM 源)
Future<String> jmGetRanking({
  required String category,
  required String order,
  required int page,
}) => RustLib.instance.api.crateBridgeJmGetRanking(
  category: category,
  order: order,
  page: page,
);
